models/Fanpage.php
<?php
namespace app\models;

use app\components\Model;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "fanpage".
 *
 * @property integer               $id
 * @property integer               $company_id
 * @property integer               $fb_page_id
 * @property string                $access_token
 * @property string                $expire_date
 * @property integer               $is_join
 * @property string                $create
 * @property string                $name
 *
 * @property Category[]            $categories
 * @property Comment[]             $comments
 * @property Conversation[]        $conversations
 * @property Company               $company
 * @property Product               $products
 * @property Inbox[]               $inboxes
 * @property PageConfig[]          $pageConfigs
 * @property PageConfigReply[]     $pageConfigReplies
 * @property Post[]                $posts
 * @property User[]                $users
 * @property ProductFanpage[]      $productFanpages
 * @property PromotionPage[]       $promotionPages
 * @property ReportComment[]       $reportComments
 * @property ReportCustomer[]      $reportCustomers
 * @property ReportCustomerOrder[] $reportCustomerOrders
 * @property ReportInbox[]         $reportInboxes
 * @property ReportProduct[]       $reportProducts
 * @property ReportRevenue[]       $reportRevenues
 * @property ReportShipping[]      $reportShippings
 * @property UserFanpage[]         $userFanpages
 */
class Fanpage extends Model {

	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return 'fanpage';
	}

	const IS_JOIN  = [
		'Chưa join',
		'Đã join',
	];

	const JOINED   = 1;

	const NOT_JOIN = 0;

	/**
	 * @inheritdoc
	 */
	public function rules() {
		return [
			[
				['company_id'],
				'required',
			],
			[
				[
					'company_id',
					'fb_page_id',
					'is_join',
				],
				'integer',
			],
			[
				[
					'expire_date',
					'create',
				],
				'safe',
			],
			[
				[
					'access_token',
					'name',
				],
				'string',
				'max' => 255,
			],
			[
				['company_id'],
				'exist',
				'skipOnError'     => true,
				'targetClass'     => Company::className(),
				'targetAttribute' => ['company_id' => 'id'],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels() {
		return [
			'id'           => 'ID',
			'company_id'   => 'Company ID',
			'page_id'      => 'Page ID',
			'access_token' => 'Access Token',
			'expire_date'  => 'Expire Date',
			'is_join'      => 'Is Join',
			'create'       => 'Create',
			'name'         => 'Name',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getCategories() {
		return $this->hasMany(Category::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getComments() {
		return $this->hasMany(Comment::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getConversations() {
		return $this->hasMany(Conversation::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getCompany() {
		return $this->hasOne(Company::className(), ['id' => 'company_id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getInboxes() {
		return $this->hasMany(Inbox::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getPageConfigs() {
		return $this->hasMany(PageConfig::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getPageConfigReplies() {
		return $this->hasMany(PageConfigReply::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getPosts() {
		return $this->hasMany(Post::className(), ['fanpage_id' => 'id']);
	}

	public function getUsers() {
		return $this->hasMany(User::className(), ['id' => 'user_id'])->via('userFanpages');
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getProductFanpages() {
		return $this->hasMany(ProductFanpage::className(), ['fanpage_id' => 'id']);
	}

	public function getProducts() {
		return $this->hasMany(Product::className(), ['id' => 'product_id'])->via('productFanpages');
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getPromotionPages() {
		return $this->hasMany(PromotionPage::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportComments() {
		return $this->hasMany(ReportComment::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportCustomers() {
		return $this->hasMany(ReportCustomer::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportCustomerOrders() {
		return $this->hasMany(ReportCustomerOrder::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportInboxes() {
		return $this->hasMany(ReportInbox::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportProducts() {
		return $this->hasMany(ReportProduct::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportRevenues() {
		return $this->hasMany(ReportRevenue::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getReportShippings() {
		return $this->hasMany(ReportShipping::className(), ['fanpage_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUserFanpages() {
		return $this->hasMany(UserFanpage::className(), ['fanpage_id' => 'id']);
	}

	public function setActive() {
		$fanpages      = $this->user->fanpages;
		$fanpage_array = ArrayHelper::map($fanpages, 'id', 'id');
		$class_active  = '';
		if($fanpages) {
			if(reset($fanpage_array) == $this->id) {
				$class_active = "active";
			}
		}
		return $class_active;
	}
}

controllers/FanpageController.php
<?php
namespace app\controllers;

use Yii;
use app\models\Fanpage;
use app\models\FanpageSearch;
use yii\authclient\clients\Facebook;
use yii\authclient\OAuth2;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FanpageController implements the CRUD actions for Fanpage model.
 */
class FanpageController extends Controller {

	public $enableCsrfValidation = false;

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * Lists all Fanpage models.
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new FanpageSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		return $this->render('index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionSelectPage() {
		$facebook               = new Facebook();
		$facebook->clientSecret = Yii::$app->authClientCollection->clients['facebook']->clientSecret;
		$fb                     = $facebook->api('me/accounts', 'GET');
		foreach($fb['data'] as $item) {
			$fb_id   = $item['id'];
			$fanpage = Fanpage::find()->where("fb_page_id = '$fb_id'")->one();
			if(!$fanpage) {
				$fanpage               = new Fanpage();
				$fanpage->is_join      = 0;
				$fanpage->company_id   = Yii::$app->user->identity->company_id;
				$fanpage->name         = $item['name'];
				$fanpage->fb_page_id   = $fb_id;
				$fanpage->access_token = $item['access_token'];
				$fanpage->create       = date('Y-m-d H:i:s');
				$fanpage->save();
			} else {
				$fanpage->updateAttributes(['name' => $item['name']]);
			}
		}
		if(Yii::$app->request->post()) {
			foreach(Yii::$app->request->post()['Fanpage'] as $item) {
				$page = Fanpage::findOne(['fb_page_id' => $item['join']]);
				if($page) {
					$page->updateAttributes(['is_join' => $page::JOINED]);
				}
			}
			return $this->redirect(['fanpage']);
		}
		return $this->render('select-page', [
			'fbPages' => $fb,
		]);
	}

	public function actionFanpage() {
		$facebook               = new Facebook();
		$facebook->clientSecret = Yii::$app->authClientCollection->clients['facebook']->clientSecret;
		//		$fb                     = $facebook->api('me/accounts', 'GET');
		$companyId = Yii::$app->user->identity->company_id;
		$fb_pages  = Fanpage::find()->where("company_id = '$companyId' and is_join = 1")->all();
		return $this->render('fanpage', [
			'fb_pages' => $fb_pages,
		]);
	}

	/**
	 * Displays a single Fanpage model.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionView($id) {
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new Fanpage model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new Fanpage();
		if($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect([
				'view',
				'id' => $model->id,
			]);
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Updates an existing Fanpage model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel($id);
		if($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect([
				'view',
				'id' => $model->id,
			]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	public function actionDeleteJoin() {
		if($data_post = Yii::$app->request->post()) {
			if(isset($data_post['id'])) {
				$id    = $data_post['id'];
				$model = $this->findModel($id);
				$model->updateAttributes(['is_join' => $model::NOT_JOIN]);
				return true;
			} else {
				return false;
			}
		}
		return false;
	}

	/**
	 * Deletes an existing Fanpage model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionDelete($id) {
		$this->findModel($id)->delete();
		return $this->redirect(['index']);
	}

	/**
	 * Finds the Fanpage model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 *
	 * @return Fanpage the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if(($model = Fanpage::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

views/fanpage/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Fanpage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fanpage-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'company_id')->textInput() ?>

    <?= $form->field($model, 'page_id')->textInput() ?>

    <?= $form->field($model, 'access_token')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'expire_date')->textInput() ?>

    <?= $form->field($model, 'is_join')->textInput() ?>

    <?= $form->field($model, 'create')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/fanpage/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FanpageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fanpage-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'company_id') ?>

    <?= $form->field($model, 'page_id') ?>

    <?= $form->field($model, 'access_token') ?>

    <?= $form->field($model, 'expire_date') ?>

    <?php // echo $form->field($model, 'is_join') ?>

    <?php // echo $form->field($model, 'create') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/fanpage/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Fanpage */

$this->title = 'Create Fanpage';
$this->params['breadcrumbs'][] = ['label' => 'Fanpages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fanpage-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/fanpage/fanpage.php
<?php
/**
 * Created by PhpStorm.
 * User: luong
 * Date: 03/02/2017
 * Time: 3:00 PM
 */
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title                   = "Fanpage đã chọn";
$this->params['breadcrumbs'][] = "Fanpage";
?>

<div class="page-content">
	<div class="page-header">
		<h1>
			Fanpage đã chọn
			<small>
				<i class="icon-double-angle-right"></i>
				Danh sách fanpage
			</small>
		</h1>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<?php foreach($fb_pages as $fb) { ?>
				<div class="col-md-3">
					<div class="checkbox">
						<label>
							<span class="lbl"><i class="icon-facebook-sign"></i> <?= $fb->name ?></span>
						</label>
						<a href="#" data-href="<?= Url::to(['/fanpage/delete-join']) ?>" data-id=<?= $fb->id ?> class="tooltip-error delete-page" data-rel="tooltip" title=""
						data-original-title="Delete">
						<span class="red">
          <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
						</span>
						</a>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
	<div class="clearfix" style="margin-top: 30px">
		<div class="col-md-offset-5 col-md-3">
			<a class="btn btn-info" href="<?php echo yii::$app->urlManager->createUrl(['fanpage/select-page']) ?>" style="color: #000000">
				<i class="icon-ok bigger-110"></i> Thêm fanpage mới
			</a>
		</div>
	</div>
</div>
<script>

</script>

views/fanpage/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FanpageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Fanpages';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fanpage-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Fanpage', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'company_id',
            'page_id',
            'access_token',
            'expire_date',
            // 'is_join',
            // 'create',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/fanpage/select-page.php
<?php
/**
 * Created by PhpStorm.
 * User: luong
 * Date: 03/02/2017
 * Time: 3:00 PM
 */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\widgets\Breadcrumbs;

$this->title                   = "Chọn fanpage";
$this->params['breadcrumbs'][] = "Fanpage";
?>

<div class="page-content">
	<div class="page-header">
		<h1>
			Chọn fanpage
			<small>
				<i class="icon-double-angle-right"></i>
				Danh sách fanpage
			</small>
		</h1>
	</div>
	<?php $form = ActiveForm::begin() ?>

	<div class="row">
		<div class="col-xs-12">

			<?php
			$i = 1;
			foreach($fbPages['data'] as $fb) { ?>
				<div class="col-md-4">
					<div class="checkbox">
						<?= Html::checkbox('Fanpage[' . $i . '][join]', false, [
							'class' => 'page-checkbox',
							'value' => $fb['id'],
						]) ?>
						<span class="lbl">
							<img src="//graph.facebook.com/<?= $fb['id'] ?>/picture"> <?= $fb['name'] ?></span>
					</div>
				</div>
				<?php $i ++;
			} ?>

		</div>
	</div>
	<div class="clearfix" style="margin-top: 30px">
		<div class="col-md-offset-5 col-md-3">
			<?= Html::submitButton('<i class="icon-ok bigger-110"></i> Chọn', ['class' => 'btn btn-info']) ?>
		</div>
	</div>
	<?php ActiveForm::end() ?>

</div>

views/fanpage/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Fanpage */

$this->title = 'Update Fanpage: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Fanpages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="fanpage-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/fanpage/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Fanpage */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Fanpages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fanpage-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'company_id',
            'page_id',
            'access_token',
            'expire_date',
            'is_join',
            'create',
        ],
    ]) ?>

</div>